eigen practice
shaohedu/XcodeLeetcode pull request #4
Opened 2021-07-18 08:24 UTC by shaohedu

Eigen 基本应用案例练习，不用详细看

2021-07-18 20:04 UTC, jpxthu requested changes
https://google.github.io/styleguide/cppguide.html

如果决定遵守，建议通读，或者拿捏不准的时候去搜一下，这个规范规定得非常严格，基本上每一行代码都有标准答案。

2021-07-18 20:04 UTC, jpxthu commented on Leetcode/EigenDemo/eigenPractice.cpp
> +    m(1,1) = m(1,0) + m(0,1);
```suggestion
    MatrixXd m(2, 2);
    m(0, 0) = 3;
    m(1, 0) = 2.5;
    m(0, 1) = -1;
    m(1, 1) = m(1, 0) + m(0, 1);
```

2021-07-18 20:04 UTC, jpxthu commented on Leetcode/EigenDemo/eigenPractice.hpp
> +using namespace Eigen;
大工程里尽可能避免 using namespace 避免造成不必要的混淆，尤其在头文件里。

2021-07-18 20:04 UTC, jpxthu commented on Leetcode/EigenDemo/eigenPractice.hpp
> +#define MATRIX_SIZE 50
Use `constexpr` instead in `C++`. Use `define` in `C` because `constexpr` is a `C++` feature.

2021-07-18 20:04 UTC, jpxthu commented on Leetcode/EigenDemo/eigenPractice.cpp
> +    std::cout << "time of normal inverse is " << 1000 * (clock() - time_stt) / (double) CLOCKS_PER_SEC << "ms" << std::endl;
目测这行太长了。给自己定一个最大行宽，一般是水平分割两个窗口可以不出横向滚动条的宽度，这样看起来比较方便。主流 1080p 的话一般这个数值是 80-100 个字符。这个 Google C++ Style Guide 给的是 80，公司可能会自己定。

https://google.github.io/styleguide/cppguide.html#Line_Length

2021-07-18 20:04 UTC, jpxthu commented on Leetcode/EigenDemo/eigenPractice.cpp
> +    std::cout << "time of normal inverse is " << 1000 * (clock() - time_stt) / (double) CLOCKS_PER_SEC << "ms" << std::endl;
在 C++ 里强制类型转换用：
``` cpp
static_cast<double>(var)
```

2021-07-18 20:04 UTC, jpxthu commented on Leetcode/EigenDemo/eigenPractice.hpp
> +#include "Eigen/Dense"
``` cpp
#include "Eigen/Eigen"
```
就可以了。

2021-07-18 20:04 UTC, jpxthu commented on Leetcode/EigenDemo/eigenPractice.hpp
> +#define eigenPractice_hpp
https://google.github.io/styleguide/cppguide.html#The__define_Guard

The format of the symbol name should be `<PROJECT>_<PATH>_<FILE>_H_`.

2021-07-18 20:04 UTC, jpxthu commented on Leetcode/EigenDemo/eigenPractice.hpp
> +#include <iostream>
顺序错了，已经第三次说了。仔细一点。

2021-07-18 20:04 UTC, jpxthu commented on Leetcode/EigenDemo/eigenPractice.cpp
> +    std::cout <<"x = " << x.transpose() << std::endl;
```suggestion
    std::cout << "x = " << x.transpose() << std::endl;
```

2021-07-18 20:04 UTC, jpxthu commented on Leetcode/EigenDemo/eigenPractice.cpp
> +    std::cout <<"x = " << x.transpose() << std::endl;
```suggestion
    std::cout << "x = " << x.transpose() << std::endl;
```

2021-07-18 20:04 UTC, jpxthu commented on Leetcode/EigenDemo/eigenPractice.cpp
> +    std::cout << "time of Qr decomposition is " << 1000 * (clock() - time_stt) / (double) CLOCKS_PER_SEC << "ms" << std::endl;
ditto

2021-07-18 20:04 UTC, jpxthu commented on Leetcode/EigenDemo/eigenPractice.cpp
> +    std::cout << "time of ldlt decomposition is " << 1000 * (clock() - time_stt) / (double) CLOCKS_PER_SEC << "ms" << std::endl;
ditto

2021-07-18 20:04 UTC, jpxthu commented on Leetcode/EigenDemo/eigenPractice.cpp
> +    Vector3d euler_angles = rotation_matrix.eulerAngles(2, 1, 0); // ZYX
```suggestion
    Vector3d euler_angles = rotation_matrix.eulerAngles(2, 1, 0);  // ZYX
```

https://google.github.io/styleguide/cppguide.html#Implementation_Comments

These end-of-line comments should be separated from the code by 2 spaces.

2021-07-18 20:04 UTC, jpxthu commented on Leetcode/EigenDemo/main.cpp
> +#include "eigenPractice.hpp"
```suggestion
#include "eigen_practice.hpp"
```

https://google.github.io/styleguide/cppguide.html#File_Names

Filenames should be all lowercase and can include underscores (\_) or dashes (-). Follow the convention that your project uses. If there is no consistent local pattern to follow, prefer "\_".

2021-07-18 20:04 UTC, jpxthu commented on Leetcode/EigenDemo/eigenPractice.hpp
> +class eigenPractice {
```suggestion
class EigenPractice {
```

https://google.github.io/styleguide/cppguide.html#Type_Names

Type names start with a capital letter and have a capital letter for each new word, with no underscores.

2021-07-18 20:04 UTC, jpxthu commented on Leetcode/EigenDemo/eigenPractice.hpp
> +public:
```suggestion
  public:
```

https://google.github.io/styleguide/cppguide.html#Class_Format

The public:, protected:, and private: keywords should be indented one space.
但你没有用 2 个空格作为缩进，这里可以进两格。

2021-07-18 20:04 UTC, jpxthu commented on Leetcode/EigenDemo/eigenPractice.hpp
> +    void eigenGeometry();
```suggestion
    void EigenBasic();
    void EigenGeometry();
```

https://google.github.io/styleguide/cppguide.html#Function_Names

2021-07-18 20:04 UTC, jpxthu commented on Leetcode/EigenDemo/eigenPractice.hpp
> +#endif /* eigenPractice_hpp */
```suggestion
#endif  // eigenPractice_hpp
```

https://google.github.io/styleguide/cppguide.html#Namespace_Formatting

也许可以跟着 namespace 的规矩来。至少遵守行位注释两格空格的规则。

2021-07-18 20:04 UTC, jpxthu commented on Leetcode/EigenDemo/eigenPractice.cpp
> +        for (int j = 0; j < 3; j++) std::cout << matrix_23(i, j) << "\t";
```suggestion
        for (int j = 0; j < 3; j++)
            std::cout << matrix_23(i, j) << "\t";
```

https://google.github.io/styleguide/cppguide.html#Conditionals
https://google.github.io/styleguide/cppguide.html#Loops_and_Switch_Statements

不太建议单行写完。

2021-07-18 20:04 UTC, jpxthu commented on Leetcode/EigenDemo/eigenPractice.cpp
> +    std::cout << "rotation matrix = \n" << rotation_vector.matrix() << std::endl;
尽可能用 `std::endl` 代替 `\n`，如果在 Windows 下运行，换行是 `\r\n`。

2021-07-18 20:07 UTC, jpxthu commented
如果 reviewer 没有 approve，标准做法是改完 push 一个或多个新的 commit，然后点 re-request review，approve 之后再 merge。

2021-07-19 16:38 UTC, jpxthu requested changes

2021-07-19 16:38 UTC, jpxthu commented on Leetcode/EigenDemo/main.cpp
>  #include <iostream>
```suggestion
```

https://google.github.io/styleguide/cppguide.html#Include_What_You_Use

不用就删掉。

2021-07-19 16:38 UTC, jpxthu commented on Leetcode/EigenDemo/eigen_practice.hpp
> +constexpr int MATRIX_SIZE = 50;
放到 .cpp 里面去，头文件里并没有用它。头文件只暴露必要的信息。

https://google.github.io/styleguide/cppguide.html#Include_What_You_Use

2021-07-19 16:38 UTC, jpxthu commented on Leetcode/EigenDemo/eigen_practice.hpp
> +constexpr int MATRIX_SIZE = 50;
```suggestion
constexpr int kMatrixSize = 50;
```

https://google.github.io/styleguide/cppguide.html#Constant_Names

2021-07-19 16:38 UTC, jpxthu commented on Leetcode/EigenDemo/eigen_practice.hpp
> +#include <stdio.h>
这个是干嘛用的？`clock()` 吗？

尽可能避免使用 C 库和头文件。C 没有 namespace 保护，语法和编译方式都有区别。大部分 C 标准库都有 C++ 版本，去掉 `.h` 前面加 `c`，比如 `<cstdio>`。时间相关函数在 `<ctime>` 里，封装在 `namespace std` 里：
``` cpp
std::clock_t t = std::clock();
```

https://en.cppreference.com/w/cpp/header/ctime

2021-07-20 11:54 UTC, shaohedu commented on Leetcode/EigenDemo/eigen_practice.hpp
> +#include <stdio.h>
不需要 <ctime>, clock()也可以调用

2021-07-20 12:31 UTC, jpxthu commented on Leetcode/EigenDemo/eigen_practice.hpp
> +#include <stdio.h>
https://google.github.io/styleguide/cppguide.html#Include_What_You_Use
根据这个原则，你还是应该引用 <ctime>。何况 <iostream> 里并不包涵 <ctime> 的引用，`clock()` 是 <iostream> 里引用了 <time.h>，其实是不建议用的，很容易混淆 `::clock()` 和 `std::clock()`。以及需要注意的是，C++ Standard 里并没有规定 `time_t(0)` 是否是 `1970-01-01T00:00Z`，这个是不可以用来作为绝对时间的。
https://stackoverflow.com/questions/6012663/get-unix-timestamp-with-c

2021-07-20 12:33 UTC, jpxthu approved these changes

2021-07-20 12:33 UTC, jpxthu commented on Leetcode/EigenDemo/eigen_practice.cpp
> +    1000 * (clock() - time_stt) / static_cast<double>(CLOCKS_PER_SEC) << "ms" << std::endl;
这里还有一个简单的写法是：
```suggestion
    1000.0 * (clock() - time_stt) / CLOCKS_PER_SEC << "ms" << std::endl;
```
抱歉之前看漏了。

2021-07-20 12:57 UTC, merged