Binary tree
shaohedu/XcodeLeetcode pull request #5
Opened 2021-07-22 14:16 UTC by shaohedu

1. 重新定下规则：class 数据命名 public 用 mixed case，第一个字母小写 eg. binaryTree; protected 和 private在前边加下划线 _binaryTree
2. main函数运行时，系统内存一直在上涨

2021-07-22 14:21 UTC, shaohedu commented on Leetcode/tree/main.cpp
> +}
内存一直在飙，帮忙看下，提些debug思路吧，谢谢～

2021-07-23 07:59 UTC, jpxthu requested changes

2021-07-23 07:59 UTC, jpxthu commented on Leetcode/tree/binary_tree.cpp
> +#include <iostream>
```suggestion
#include <iostream>
#include <vector>
```

2021-07-23 07:59 UTC, jpxthu commented on Leetcode/tree/binary_tree.cpp
> +    }
``` c++
    if (data == -1) {
        return;
    } else {
        if (data == -2) {
            tree = nullptr;
        } else {
            std::cout << "debug 2" << std::endl;
            tree = new TreeNode;
            tree->data = data;
            CreatBTree(tree->left);
            CreatBTree(tree->right);
        }
    }
```

https://google.github.io/styleguide/cppguide.html#Conditionals
在 else 后面有大括号的时候，if 后面也加大括号会比较整齐。

``` c++
    if (data == -1) {
        return;
    }
    if (data == -2) {
        tree = nullptr;
    } else {
        std::cout << "debug 2" << std::endl;
        tree = new TreeNode;
        tree->data = data;
        CreatBTree(tree->left);
        CreatBTree(tree->right);
    }
```

这样也可以，还可以减少后面的缩进长度。

2021-07-23 07:59 UTC, jpxthu commented on Leetcode/tree/binary_tree.cpp
> +                                                TreeNode* root) {
缩进？

2021-07-23 07:59 UTC, jpxthu commented on Leetcode/tree/binary_tree.cpp
> +void BTree::PreOrderTraversal(TreeNode* root, std::vector<int>& temp) {
不要用 temp 这样的变量名，没有可读性。

2021-07-23 07:59 UTC, jpxthu commented on Leetcode/tree/binary_tree.hpp
> +#include <stack>
order

2021-07-23 07:59 UTC, jpxthu commented on Leetcode/tree/main.cpp
> +}
CreateBTree 一直在加节点，内存肯定会涨，你打断点确认到底是哪里在涨。

2021-07-23 07:59 UTC, jpxthu commented on Leetcode/tree/main.cpp
> +    std::vector<int> result = bTree.Traversal(orderType, &tree);
把 tree 指针作为一个成员变量存在 bTree 的 class 里，或者把 bTree class 所有的函数弄成开放函数或者 static function。现在这个 class 设计很怪。

2021-07-23 08:09 UTC, jpxthu commented
>     1. 重新定下规则：class 数据命名 public 用 mixed case，第一个字母小写 eg. binaryTree; protected 和 private在前边加下划线 _binaryTree
> 
>     2. main函数运行时，系统内存一直在上涨

把你额外定的规矩写个 .md 放在 codebase 里。

2021-07-26 10:49 UTC, jpxthu requested changes

2021-07-26 10:49 UTC, jpxthu commented on Leetcode/tree/binary_tree.cpp
> +                           TreeNode* tree_root, int iterator) {
还是没对齐啊，你 IDE 是不是没设置对，还是用了 tab，还是没有用等宽字体，还是没认真检查？

2021-07-26 10:49 UTC, jpxthu commented on 代码规范.md
> +1. class 数据命名 public 用 mixed case，第一个字母小写 eg. binaryTree; protected 和 private在前边加下划线 _binaryTree
```suggestion
### class 数据命名
1. public 变量用 mixed case，第一个字母小写，eg. binaryTree。
2. protected 和 private 变量在前边加下划线：_binaryTree。
3. 成员函数使用默认规则。
```

```suggestion
1. class 数据命名：public 变量用 mixed case，第一个字母小写，eg. binaryTree；protected 和 private 变量在前边加下划线，比如 _binaryTree。
```

务必统一中英文标点和格式，注意语法并正确使用标点符号。
https://github.com/mzlogin/chinese-copywriting-guidelines/blob/Simplified/README.md

2021-07-26 10:49 UTC, jpxthu commented on 代码规范.md
> +# 代码规范
需要说明这个是 [Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html) 的修正。

2021-07-26 10:49 UTC, jpxthu commented on Leetcode/tree/binary_tree.hpp
> +};
> 把 tree 指针作为一个成员变量存在 bTree 的 class 里，或者把 bTree class 所有的函数弄成开放函数或者 static function。现在这个 class 设计很怪。

这个你没有改。开放函数指的是去掉 class，不是 public。

2021-07-26 10:49 UTC, jpxthu commented on Leetcode/tree/main.cpp
> +    TreeNode* tree = new TreeNode;
new 的指针在 23 行直接被覆盖掉了，原来的指针变成野指针，没有 free。new 指针操作容易出错，很多时候你不知道这个指针是在哪里 new 的，要用多久，还是一个实体变量的引用。Google 要求用 smart pointer。如果要 new，建议在 class 的构造函数里 new 成员变量，并在析构函数中 free 掉，不要在 class 以外 new。

2021-07-26 10:49 UTC, jpxthu commented on Leetcode/tree/binary_tree.cpp
> +                           TreeNode* tree_root, int iterator) {
```suggestion
TreeNode* BTree::CreatBTree(const std::vector<int>& level_order, int iterator) {
```

2021-07-26 10:49 UTC, jpxthu commented on Leetcode/tree/binary_tree.cpp
> +                           TreeNode* tree_root, int iterator) {
这个 class 设计非常怪，重写一下吧。这个函数也根本不需要 `tree_root` 这个输入，没有起到任何作用。

2021-07-26 10:49 UTC, jpxthu commented on Leetcode/tree/binary_tree.hpp
> +};
```suggestion
class BTree {
  public:
    BTree(const std::vector<int>& level_order) {
        _root = new TreeNode();
        // ...
    }
    ~BTree() {  // 确保 free 掉每一个 node，可以在 `TreeNode` 析构函数里打 log 来 debug。
        if (_root) {
            _root->~TreeNode();
            free(_root);
        }
    }
    TreeNode* root() const {
        return _root;
    }
    std::vector<int> Traversal(BTreeOrderType order_type) {
        std::vector<int> result;
        switch (order_type) {
            // ...
        }
        return result;
    }
    std::vector<std::vector<int>> LevelTraversal() {
        std::vector<std::vector<int>> result;
        InnerLevelTraversal(_root, result, 0);
        return result;
    }

  private:
    TreeNode* CreatSubTree(const std::vector<int>& level_order, int iterator);
    void PreOrderTraversal(TreeNode* node, std::vector<int>& result);
    void InOrderTraversal(TreeNode* node, std::vector<int>& result);
    void PostOrderTraversal(TreeNode* node, std::vector<int>& result);
    void InnerLevelTraversal(TreeNode* node, std::vector<std::vector<int>>& result, int depth);

    TreeNode* _root = nullptr;
};
```

2021-07-26 10:49 UTC, jpxthu commented on Leetcode/tree/binary_tree.cpp
> +        tree_root = tree;
对输入指针进行地址操作（重定向）是没有任何意义的。

2021-07-26 10:49 UTC, jpxthu commented on Leetcode/tree/binary_tree.cpp
> +        tree->right = nullptr;
下面对 left 和 right 都赋值了，这两行完全没有意义。而且 `TreeNode` 的默认构造函数本身就应该给定 nullptr 的初始值。

2021-07-26 10:49 UTC, jpxthu commented on Leetcode/tree/binary_tree.cpp
> +        TreeNode* tree = new TreeNode;
```suggestion
        TreeNode* tree = new TreeNode();
```

2021-07-26 10:49 UTC, jpxthu commented on Leetcode/tree/binary_tree.hpp
> +};
```suggestion
struct TreeNode {
    TreeNode() {}
    ~TreeNode() {
        if (left) {
            left->~TreeNode();
            free(left);
        }
        if (right) {
            right->~TreeNode();
            free(right);
        }
    }
    int data = 0;
    TreeNode* left = nullptr;
    TreeNode* right = nullptr;
};
```

2021-07-26 10:49 UTC, jpxthu commented on Leetcode/tree/binary_tree.hpp
> +#ifndef TREE_BINARY_TREE
```suggestion
#ifndef TREE_BINARY_TREE_HPP
```

https://google.github.io/styleguide/cppguide.html#The__define_Guard

2021-07-26 10:49 UTC, jpxthu commented on Leetcode/tree/binary_tree.hpp
> +#include <stack>
有用到 stack 吗？

2021-07-26 10:49 UTC, jpxthu commented on Leetcode/tree/main.cpp
> +    //8  9 0
```suggestion
    // 8  9 0
```

2021-07-26 15:10 UTC, jpxthu requested changes

2021-07-26 15:10 UTC, jpxthu commented on 代码规范.md
> +[Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html) 的修正
https://github.com/shaohedu/XcodeLeetcode/blob/23ff0e0ffebf038e1b0c4c7719a957165ed603ec/%E4%BB%A3%E7%A0%81%E8%A7%84%E8%8C%83.md
你看一眼这个 md 的 preview。

2021-07-26 15:10 UTC, jpxthu commented on Leetcode/tree/binary_tree.hpp
> +            std::cout << "free left node" << std::endl;
Include `iostream`

2021-07-26 15:10 UTC, jpxthu commented on Leetcode/tree/binary_tree.hpp
> +        std::cout << "~TreeNode() succeed" << std::endl;
你可以把 this->data 输出出来。

2021-07-26 15:10 UTC, jpxthu commented on Leetcode/tree/binary_tree.hpp
> +    TreeNode* left = nullptr;
无论是字母顺序还是习惯，都应该 left 在前面。类似的还有 lower/upper bound。

2021-07-26 15:10 UTC, jpxthu commented on Leetcode/tree/binary_tree.hpp
> +    explicit TreeNode() { }
```suggestion
    explicit TreeNode() {}
```

规范里面全是 `{}`，搜不到 `{ }`。

2021-07-26 15:10 UTC, jpxthu commented on Leetcode/tree/binary_tree.hpp
> +    ~TreeNode() {
这个函数不算短，都放去 .cc 里。我 comment 只是为了方便。

2021-07-26 15:10 UTC, jpxthu commented on Leetcode/tree/binary_tree.hpp
> +    PostOrder = 2,
https://google.github.io/styleguide/cppguide.html#Enumerator_Names

2021-07-27 13:52 UTC, shaohedu commented on Leetcode/tree/binary_tree.hpp
> +    PostOrder = 2,
按我司规范是对的，更新到.md了

2021-07-27 14:26 UTC, jpxthu approved these changes

2021-07-27 14:26 UTC, jpxthu commented on Leetcode/tree/binary_tree.hpp
> +#include <iostream>
用 std::cout 的析构函数已经放在 .cc 里了，头文件也不应该放在 .hpp 里。

2021-07-27 15:00 UTC, merged